name: Build and Package Python Application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Copy image files to build directory
      run: |
        xcopy /E /I images\* %GITHUB_WORKSPACE%\dist\images

    - name: Package with PyInstaller
      run: |
        pyinstaller --onefile youur_script.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: packaged-exe
        path: dist/your_script.exe
